### PR TITLE
Remove template from functions.

### PR DESCRIPTION
**Pull request by luca-heltai**
This passage is useful for the pi-domus revolution. It is an incompatible change, which would free us from the necessity to have a component in the Interface.

### CODE REVIEW

**Comment by luca-heltai** [comment]
Closes #243

**Comment by asartori86** [comment]
grazie! gli examples e le app le aggiorniamo in un'altra PR?

**Comment by luca-heltai** [comment]
None of the examples needed anything for this (but there were two tiny problems with parsed_data_out). The branch is ready to merge.

**Comment by asartori86** [comment]
stokes ha parecchie parsed_functions

```
  ParsedFunction<dim, dim+1>        exact_solution;
  ParsedFunction<dim, dim+1>        forcing_term;

  ParsedFunction<dim, dim+1>        initial_solution;
  ParsedFunction<dim, dim+1>        initial_solution_dot;
  ParsedDirichletBCs<dim,dim,dim+1> dirichlet_bcs;
  ParsedDirichletBCs<dim,dim,dim+1> dirichlet_dot;
```

e heat_ida

```
  ParsedFunction<dim, 1>        exact_solution;
  ParsedFunction<dim, 1>        forcing_term;

  ParsedFunction<dim, 1>        initial_solution;
  ParsedFunction<dim, 1>        initial_solution_dot;
  ParsedDirichletBCs<dim,dim,1> dirichlet_bcs;

```

**Comment by luca-heltai** [comment]
mmmm... a me ha compilato e girato... aspe che ranzo tutto

**Pull request merged**
