### PR TITLE
Fix release tests

### PR DESCRIPTION
**Pull request by asartori86**
Travis does both debug and release tests

fixed AssertThrow in parsed_mapped_functions

### CODE REVIEW

**Comment by asartori86** [comment]
```
99% tests passed, 1 tests failed out of 176
Total Test time (real) = 1109.01 sec
The following tests FAILED:
    174 - tests/utilities_02.release (Timeout)
Errors while running CTest
```

this test keeps going in timeout on travis

**Comment by luca-heltai** [comment]
I see no apparent problem on this test.... Maybe in optimized mode something is not working for the creation of directories... @ESeNonFossiIo ?

**Comment by asartori86** [comment]
Sometimes, in the previous PRs, also in debug mode that test went in Timeout

**Comment by ESeNonFossiIo** [comment]
@asartori86 : can you find which function requires so much time?
This is very unexpected to me.
The only function that require a while-loop is _get_next_avaible_directory_name_ but this loop seems to be well defined.

**Pull request merged**
