### PR TITLE
added val() and to_double() functions. Created new SacadoTools namespace

### PR DESCRIPTION
**Pull request by asartori86**
it turns out that these functions are useful working with pi-DoMUS.

 The `Val()` function can be called when a mixed energetic and residual formulation is given. Once the variables have been computed with the energytype, there is no need to recompute the same variable (and call another reinit of fe_cache), instead we can now do as follows

```
EnergyType dummy=0;
Tensor<2,dim,EnergyType> grad_us = fe_cache.get_gradients("solution", "grad_u", displacement, dummy);
...
Tensor<2,dim,ResidualType> grad_us_res = DOFUtilities::Val(grad_us);
```

the `sacado_to_double` should be self explanatory :)

### CODE REVIEW

**Comment by luca-heltai** [comment]
Why do you want to call it `Val` with capital `V`? This is in Sacado convention, but we stick to dealii conventions. 

For this and other things, we should make a deal2lkit::Sacado namespace, and use simple names: `val`, for example, and `to_double` (that this is a Sacado operation is taken from the namespace).

Codes would look like

```
using namespace deal2lkit::Sacado;

...
b =  to_double(a);
c =  val(d);
```

**Comment by luca-heltai** [comment]
This would also allow to use the same name for `scalar_product`, and `inner_product`, instead of having to use two different names.

**Comment by asartori86** [comment]
good points :). I'll do that

**Comment by asartori86** [comment]
should I put inside the namespace also the get_gradients etc?

**Comment by luca-heltai** [comment]
Everything which is specific to dealing with Sacado types should go in such a namespace. Think of it as a header file that could go directly into deal.II...

**Comment by asartori86** [comment]
as it is now it is inside a namespace called DOFUtilities

**Comment by asartori86** [comment]
@luca-heltai, done

**Comment by asartori86** [comment]
ping

**Comment by asartori86** [comment]
@luca-heltai  @ESeNonFossiIo  @nicola-giuliani  ping :)

**Comment by ESeNonFossiIo** [comment]
Ho visto [#171](https://github.com/mathLab/pi-DoMUS/pull/171/files). Per me si può mergiare.

**Pull request merged**
