### PR TITLE
Started version 1.0 release process.

### PR DESCRIPTION
**Pull request by luca-heltai**
At the end of this process, we should make a tag with `v1.0.0`, and make sure that all binary files generated on Travis are deployed correctly (so that users' applications can download on their Travis machines our precompiled package, including deal.II, Trilinos, Sundials, etc.)

### CODE REVIEW

**Comment by luca-heltai** [comment]
ping?

**Comment by asartori86** [comment]
can I merge?

**Comment by asartori86** [comment]
ha generato il tar.gz? dove lo trovo?

**Comment by luca-heltai** [comment]
Yes. Is everything in place for deploying on Travis CI?

**Pull request merged**
