### PR TITLE
moving something

### PR DESCRIPTION
**Pull request by nicola-giuliani**

### CODE REVIEW

**Comment by luca-heltai** [comment]
This is what happens with this code. Do things get better if you increase the maximum number of cells?

test

**Comment by nicola-giuliani** [comment]
Actually things seem to move unti we reach the maximum number of dofs. Once we have reached it the mesh remains fixed. We have tried to play with the percentage to be coarsen but we did not get significant improvements.

**Comment by luca-heltai** [comment]
test-1

**Comment by asartori86** [comment]
test

**Comment by luca-heltai** [comment]
:+1:

**Comment by asartori86** [comment]
test

**Comment by asartori86** [comment]
global

**Comment by asartori86** [comment]
adaptive

**Comment by luca-heltai** [comment]
These look perfect. Also for the papero.

**Comment by asartori86** [comment]
moved to #150

**Pull request closed without merging**
