### PR TITLE
make deal2lkit compile with current master branch of deal.ii

### PR DESCRIPTION
**Pull request by asartori86**

### CODE REVIEW

**Comment by asartori86** [comment]
@luca-heltai could you push a version 9.0 for docker? thanks

**Comment by asartori86** [comment]
all the tests pass except those reported in issue #296 
```
The following tests FAILED:

101 - parsed_grid_generator/parsed_grid_generator_10.debug (Failed)

102 - parsed_grid_generator/parsed_grid_generator_11.debug (Failed)

103 - parsed_grid_generator/parsed_grid_generator_12.debug (Failed)

Errors while running CTest
```

@luca-heltai, should we disable such tests for now?

**Comment by luca-heltai** [comment]
Yes. Go ahead and disable those tests.

**Comment by asartori86** [comment]
closes #296

**Pull request merged**
