### PR TITLE
some slight changes in tests to make them pass

### PR DESCRIPTION
**Pull request by fsalmoir**

### CODE REVIEW

**Comment by asartori86** [comment]
@luca-heltai , this PR fixes two tests with the dev version of dealii and it breaks the backward compatibility. Should we merge it now or wait after the first release of deal2lkit in order to be fully compatible with the 8.3 of dealii?

**Comment by asartori86** [comment]
travis has the dev version of dealii... so we might create a branch 1.0 and keep the master updated with the dev of dealii

**Comment by luca-heltai** [comment]
I think we should make a 1.0 branch which is fully compatible with 8.3, and keep it updated with master as we go along...

**Comment by asartori86** [comment]
quindi questa la mergiamo per adesso e poi creaimo la 1.0?

**Pull request merged**
